on:
  workflow_dispatch:
    inputs:
      docker:
        description: 'Build Docker'
        required: true
        default: 'true'
      deploy:
        description: 'Deploy'
        required: true
        default: 'false'

name: Docker

jobs:
  docker_and_helm:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build docker
        if: github.event.inputs.docker == 'true'
        run: |
          make docker_build
          make docker_login
          make docker_publish
        env:
          CI: 'true'
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
